apiVersion: v1
kind: Service
metadata:
  name: alpha
  namespace: alpha
  labels:
    name: alpha
    app: alpha
spec:
  selector:
    name: alpha 
  type: ClusterIP
  ports:
   - name: http
     port: 80
     targetPort: 80
     protocol: TCP