apiVersion: v1
kind: Service
metadata:
  name: petclinic-frontend
  namespace: petclinic
  labels:
    name: petclinic-frontend
    app: petclinic-frontend
spec:
  selector:
    name: petclinic-frontend 
  type: ClusterIP
  ports:
   - name: http
     port: 80
     targetPort: 80
     protocol: TCP