apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic-backend
  namespace: petclinic-backend
  labels:
    name: petclinic-backend
    app: petclinic-backend
spec:
  replicas: 3
  selector:
      matchLabels:
        name: petclinic-backend
  template:
    metadata:
      labels:
        name: petclinic-backend
    spec:
      containers:
      - name: web 
        image: haroldo89/front-app:69
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 50m
            memory: 50Mi
          requests:
            cpu: 50m
            memory: 50Mi