apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kubecost
  namespace: opencost
spec:
  interval: 1m
  chart:
    spec:
      chart: cost-analyzer
      sourceRef:
        kind: HelmRepository
        name: kubecost
        namespace: opencost
      interval: 1m
